# Site settings
title: o0TT0o's Blog
header-img: img/home-bg.jpg
email: qtmagic1992@gmail.com
copyright_name: o0TT0o's project
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: /o0TT0o.github.io
twitter_username: JhumW8SmnmIXkfm
github_username:  o0TT0o
facebook_username:  profile.php?id=100013342032313
email_username:  qtmagic1992@gmail.com


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]